name: Global deploy

on:
  push:
    branches: [ "main" ]

jobs:
  sync-prod-branches:
    name: 🎉 AUTO Open PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: main_sync
          title: 'Auto PR from main to prod'
          