name: deploy

on:
  pull_request:
    branches: [ "prod" ]
  push:
    branches: [ "prod" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4          
