name: Global deploy

on:
  push:
    branches: [ "main" ]

jobs:
  sync-prod-branches:
    name: 🎉 AUTO Open PR
    runs-on: ubuntu-latest

    steps:
      - name: Open PR
        id: open_pr
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from-branch: main
          to-branch: main_sync
          repository-owner: Davidaprilio
          repository: cicd_cpanel
          
      - name: Echo mergeable PR number
        run: echo ${{ steps.open_pr.outputs.pull_number }}
          